# Generated by Django 3.0.4 on 2020-05-13 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20200513_0740'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='contentnumber',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
